image:
  file: .gitpod.Dockerfile

tasks:
  - init: sudo echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
